name: 'Update'

concurrency:
  group: update

on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore
    - docs/*
  workflow_dispatch:

jobs:
  build:
    name: Build the preview
    uses: ./.github/workflows/common.yml

  deploy:
    needs: 'build'
    name: Deploy to gh-pages
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout 📋
      uses: actions/checkout@v2

    - name: Download Built Draft
      uses: actions/download-artifact@v3
      with:
        name: draft
        path: docs

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
